version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: notesapp
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    networks:
      - app-network

  backend:
    build: ./backend
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env.production
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: